image: docker:stable

stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY_LIVE: registry.timolia.de


build_live:
  stage: build
  script:
    - docker info
    - docker login -u=$DOCKER_USERNAME_LIVE -p=$DOCKER_PASSWORD_LIVE $DOCKER_REGISTRY_LIVE
    - docker build -t $DOCKER_REGISTRY_LIVE/howto:$CI_COMMIT_REF_NAME .
    - docker push $DOCKER_REGISTRY_LIVE/howto:$CI_COMMIT_REF_NAME
  only:
    - master

deploy_live:
  stage: deploy
  image: ictu/sshpass
  script:
    - sshpass -p $HOWTO_PW ssh -o "StrictHostKeyChecking=no" howto@web-team.timolia.de
  only:
    - master
