image: docker:stable

#services:
#  - docker:18.09.7-dind


stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY_LIVE: registry.timolia.de
  DOCKER_REGISTRY_DEV: dev-registry.timolia.de
  IMAGE_NAME: howto
  DEPLOY_HOST: web-team.timolia.de
  DEPLOY_PORT: 2222
#  DOCKER_TLS_CERTDIR: ""
#  DOCKER_HOST: tcp://localhost:2375


build_live:
  stage: build
  tags:
    - docker
  script:
    - docker info
    - docker login -u=$DOCKER_USERNAME_LIVE -p=$DOCKER_PASSWORD_LIVE $DOCKER_REGISTRY_LIVE
    - docker build --network host -t $DOCKER_REGISTRY_LIVE/$IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $DOCKER_REGISTRY_LIVE/$IMAGE_NAME:$CI_COMMIT_REF_NAME
  only:
    - master

deploy_live:
  stage: deploy
  image: ictu/sshpass
  tags:
    - docker
  script:
    - sshpass -p $HOWTO_PW ssh -p $DEPLOY_PORT -o "StrictHostKeyChecking=no" howto@$DEPLOY_HOST
  only:
    - master

build_dev:
  stage: build
  tags:
    - docker
  script:
    - docker info
    - docker login -u=$DOCKER_USERNAME_DEV -p=$DOCKER_PASSWORD_DEV $DOCKER_REGISTRY_DEV
    - docker build --network host -t $DOCKER_REGISTRY_DEV/$IMAGE_NAME:dev .
    - docker push $DOCKER_REGISTRY_DEV/$IMAGE_NAME:dev
  except:
    - master

deploy_dev:
  stage: deploy
  image: ictu/sshpass
  tags:
    - docker
  script:
    - sshpass -p $HOWTO_PW_DEV ssh -o "StrictHostKeyChecking=no" howtoupdater@devnet-fast.timolia.de
  except:
    - master