site_name: Timolia Anleitung

pages:
- Über: 'index.md'
- Alle Befehle im Überblick: 'commands.md'
- Games:
  - 1vs1: 'games/1vs1.md'
- Frequently Asked Questions: 'faq.md'
- Spieler melden und Entschuldigungen: 'bans.md'
- Expert / Pro: 'premium.md'
- Das Timolia-Team:
  - Alle Teammitglieder im Überblick: 'team/team.md'
  - Aufgaben eines Teammitglieds: 'team/aufgaben.md'

theme: readthedocs
site_author: tixia UG (haftungsbeschraenkt)