site_name: Timolia HowTo
site_author: thomasgneist, Tedget
site_description: Alle wichtigen und auch unwichtigen Informationen über Timolia sind hier zu finden.
copyright: tixia UG (haftungsbeschränkt)
google_analytics: ['UA-55594495-7', 'howto.timolia.de']

pages:
- Über: 'index.md'
- Allgemeines:
  - Frequently Asked Questions: 'faq.md'
  - Alle Befehle: 'commands.md'
  - Reports und Entbannungen: 'bans.md'
  - Webseite und Forum: 'web.md'
  - TeamSpeak: 'teamspeak.md'
- Das Regelwerk:
  - Games: 'rules/games.md'
  - Erlaubte Modifikationen: 'rules/approvedmods.md'
  - CityBuild: 'rules/city.md'
  - Forum: 'rules/forum.md'
  - TeamSpeak: 'rules/teamspeak.md'
- Games Netzwerk:
  - 1vs1: 'games/1vs1.md'
  - 4rena: 'games/4rena.md'
  - Arcade: 'games/arcade.md'
  - BrainBow: 'games/brainbow.md'
  - Castles: 'games/castles.md'
  - DNA: 'games/dna.md'
  - InTime: 'games/intime.md'
  - JumpWorld: 'games/jumpworld.md'
  - Mineception: 'games/mineception.md'
  - Splun: 'games/splun.md'
  - Timolianische Spiele: 'games/tspiele.md'
- CityBuild:
  - Baugebiete: 'city/baugebiete.md'
  - Dienstleistungen: 'city/dienstleistungen.md'
- Ränge auf Timolia:
  - Premium-Ränge: 'ranks/premium.md'
  - YouTuber und VIP: 'ranks/youtube.md'
- Das Timolia-Team:
  - Alle Teammitglieder: 'team/members.md'
  - Veränderungen: 'team/changes.md'
  - Aufgabenbereiche: 'team/responsibilities.md'
  - Wie werde ich...?: 'team/apply.md'


theme: readthedocs
extra_css: [extra.css]