site_name: Timolia Anleitung

pages:
- Über: 'index.md'
- Regelwerk:
  - Games-Regeln: 'games/rules.md'
  - City-Regeln: 'city/rules.md'
- Alle Befehle im Überblick: 'commands.md'
- Games:
  - 1vs1: 'games/1vs1.md'
  - 4rena: 'games/4rena.md'
  - Arcade: 'games/arcade.md'
  - BrainBow: 'games/brainbow.md'
  - DNA: 'games/dna.md'
  - InTime: 'games/intime.md'
  - JumpWorld: 'games/jumpworld.md'
  - Splun: 'games/splun.md'
  - Timolianische Spiele: 'games/tspiele.md'
- CityBuild:
  - Baugebiete: 'city/baugebiete.md'
  - Events: 'city/events.md'
- TeamSpeak: 'teamspeak.md'
- Frequently Asked Questions: 'faq.md'
- Spieler melden und Entschuldigungen: 'bans.md'
- Expert / Pro: 'premium.md'
- YouTuber / Pro+: 'youtube.md'
- Das Timolia-Team: 'team.md'

theme: readthedocs
site_author: tixia UG (haftungsbeschraenkt)